export const routes = {
  home: "/",
  main: "/home",
  welcome: "/welcome",
  boarding: "/boarding",
  member: "/member",
  chat: "/chat",
  profile: "/profile",
  profileEdit: "/profile/edit",
  setting: "/setting",
  role: "/setting/role",
  like: "/like",
  owner: "/owner",
  project: "/project",
  projectCreate: "/project/create",
  projectEdit: "/project/edit",
  projectMember: "/project/members",
  create: "/project/create",
  chatRequest: "/chat/request",
  chatRoom: "/chat/room"
} as const;
